name: Deploy Hugo site to Pages

on:
  push:
    branches:
      - main

# Give the GitHub Actions bot permission to push to gh-pages
permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true      # fetch Hugo theme submodules
          fetch-depth: 0        # fetch full history for .GitInfo and .Lastmod

      # Step 2: Setup Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      # Step 3: Fetch Hugo Modules (fixes "partial not found" errors)
      - name: Install Hugo Modules
        run: hugo mod tidy

      # Step 4: Build the site
      - name: Build
        run: hugo --minify

      # Step 5: Deploy to gh-pages branch
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

